// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otkhxrrbiqdutlgfkfdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90a2h4cnJiaXFkdXRsZ2ZrZmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1Nzg2NDAsImV4cCI6MjA1NzE1NDY0MH0.dGD5wYO0U9BWkFbbZqA2XfXiYwDXpcZQtluKeiBPLKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a single instance of the supabase client to be used throughout the app
let supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

export const getSupabaseClient = () => {
  if (!supabaseInstance) {
    supabaseInstance = createClient<Database>(
      SUPABASE_URL, 
      SUPABASE_PUBLISHABLE_KEY,
      {
        auth: {
          storageKey: 'unineeds-auth-storage-key',
          persistSession: true,
          autoRefreshToken: true,
        }
      }
    );
  }
  return supabaseInstance;
};

// For backwards compatibility
export const supabase = getSupabaseClient();